import Head from "next/head";
import Carousel from "@/components/herosection/Carousel";
import FlashDeal from "@/components/deals/FlashDeal";
import ServiceCard from "@/components/ServiceCard";
import NewArrival from "@/components/newArrival/NewArrival";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='mx-auto w-full max-w-[1400px]'>
        <Carousel />
        <ServiceCard />
        <FlashDeal />
        <NewArrival/>
      </main>
    </>
  );
}
